# Homework #1

In [164]:
import numpy as np
import pandas as pd

## Question 1

In [165]:
np.__version__

'1.19.5'

## Question 2

In [167]:
pd.__version__

'1.3.2'

## Question 3

In [219]:
df = pd.read_csv("data.csv")

In [169]:
round(
    df[
        df["Make"] == "BMW"
    ].MSRP.mean(),
    2
)

61546.76

## Question 4

In [170]:
after_2015 = df[
    df["Year"] >= 2015
]

after_2015["Engine HP"].isnull().sum()

51

## Question 5

In [171]:
mean_hp_before = df["Engine HP"].mean()
round(mean_hp_before)

249

In [220]:
df["Engine HP"] = df["Engine HP"].fillna(mean_hp_before)

In [177]:
mean_hp_after = df["Engine HP"].mean()
round(mean_hp_after)

249

## Question 6

In [222]:
rolls_royce_rows = df[
    df["Make"] == "Rolls-Royce"
]

In [192]:
X = rolls_royce_rows[["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates().values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [204]:
XT = X.T
XTX = XT.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [205]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [206]:
round(np.sum(XTX_inv), 4)

0.0322

## Question 7

In [208]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [216]:
w = XTX_inv.dot(XT).dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])